spring:
  profiles:
    active: dev
  application:
    name: quizsushi-be
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 5000
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

admin:
  root:
    id: root
    password: ${ADMIN_ROOT_PASSWORD}
  login:
    success-url: ${ADMIN_LOGIN_SUCCESS}
    failure-url: ${ADMIN_LOGIN_FAILURE}
  logout:
    success-url: ${ADMIN_LOGOUT_SUCCESS}

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: ${KAKAO_REDIRECT_URI}
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}

app:
  frontend:
    oauth-redirect: ${FRONTEND_OAUTH_REDIRECT}

jwt:
  secret-key: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

minio:
  endpoint: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}

logging:
  level:
    root: INFO
    com.cmdlee.quizsushi: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_EXPOSURE:health,info}
  endpoint:
    health:
      show-details: ${ACTUATOR_HEALTH_DETAILS:never}