name: Deploy Backend to Server

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            dlaudfuf33/quizsushi-be:latest
            dlaudfuf33/quizsushi-be:${{ github.sha }}

      - name: SSH deploy backend container
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull dlaudfuf33/quizsushi-be:${{ github.sha }}
            docker stop quizsushi-be || true
            docker rm quizsushi-be || true
            docker stop redis || true
            docker rm redis || true
            docker network create quizsushi-net || true
            docker run -d --name redis --network quizsushi-net -p 6379:6379 redis:7
            docker run -d --name quizsushi-be \
              --network quizsushi-net \
              --env-file /home/ubuntu/docker/.env.prod \
              -p 8080:8080 \
              dlaudfuf33/quizsushi-be:${{ github.sha }}